networks:
  dns64:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.53.0.0/24
          gateway: 10.53.0.1

configs:
  unbound_config:
    content: |
      remote-control:
        control-enable: yes
      server:
        interface: 0.0.0.0
        port: 53
        chroot: ""
        username: ""

        module-config: "respip dns64 validator iterator"
        dns64-prefix: 64:ff9b::/96

        # Force ipv6 for everything
        response-ip: 0.0.0.0/0 redirect
        prefer-ip6: yes

        statistics-interval: 0
        statistics-cumulative: yes
        extended-statistics: yes

        access-control: 10.53.0.0/24 allow
        verbosity: 1
        use-syslog: no

services:
  dns64:
    build:
      context: ./dns64
    networks:
      dns64:
        ipv4_address: ${DNS64_IP}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dig", "@localhost", "-p", "53", "github.com", "aaaa"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    user: unbound
    configs:
      - source: unbound_config
        target: /usr/local/etc/unbound/unbound.conf
