include:
  - path: compose.dns64.yaml
    env_file: compose.env
  - path: compose.nat64.yaml
    env_file: compose.env
  - path: compose.hetzner.yaml
    env_file: compose.env
  - path: compose.wg.yaml
    env_file: compose.env
